spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  prject:
    version: @project.version@
  java:
    version: @java.version@
  spring:
    framework:
      version: @spring-framework.version@
    data:
      version: @spring-data-bom.version@



#info:
#  app:
#    version: @project.version@
#    java:
#      version: @java.version@
#      spring:
#        framework:
#          version: @spring-framework.version@
#        data:
#          version: @spring-data-bom.version@