spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true
  rsocket:
    server:
      # R소켓 서버 포트
      transport: tcp
      # R소켓 전송 프로토콜
      port: 7000

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

# 네티 서버 구동 포트
server:
  port: 9000


